name: Deploy to Github Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Setup Node
    - name: Use Node.js 10.x
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm install
        npm run lint
        ###
        # Configure Angular first!
        ####
        # npm test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
        # npm run webdriver-update-ci
        # npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false
        ####
        npm run ng -- deploy --name="GH Deploy" --email=gh@pages.deploy
